# .goreleaser.yml
# Configuration for GoReleaser - https://goreleaser.com
version: 2

# Global settings
project_name: multigit
env:
  - CGO_ENABLED=0
  - GO111MODULE=on

before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: 386
      - goos: windows
        goarch: arm64
    ldflags: "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}"
    binary: multigit
    main: .

archives:
  - format: binary
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^refactor:"
      - "^ci:"

release:
  github:
    owner: cpuix
    name: multigit
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Tag }}"
  extra_files:
    - glob: LICENSE
    - glob: README.md
