# Minimal golangci-lint configuration
version: v1.56.2

linters:
  # Enable only the most important linters
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple

# Don't fail on issues
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
