name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          
      - name: Check out code
        uses: actions/checkout@v3
        
      - name: Run tests
        run: |
          go test -v -coverprofile=coverage.out ./...
          go tool cover -func=coverage.out
          
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          fail_ci_if_error: true
